apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - name: "*"
      namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/jekorhon/homelab-k8s
    - https://charts.longhorn.io/ 
    - https://kubernetes-sigs.github.io/metrics-server/
