---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metric-server
  namespace: argocd
spec:
  project: homelab-config
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-server
  sources:
    - chart: metrics-server
      repoURL: https://kubernetes-sigs.github.io/metrics-server/
      targetRevision: 3.13.1
      helm:
        valuesObject:
          args:
            - --kubelet-insecure-tls
